### ISSUE TITLE
Please, add support to Net461

### ISSUE THREAD

**Issue by eduardoluizm** [PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore#14]
Hi, could you compile a new version adding a net461?

![image](https://cloud.githubusercontent.com/assets/3385836/17465872/cf38dd1c-5cd7-11e6-83bb-7fd4a09fcc2d.png)

  "frameworks": {
    "net461": {}
  }

Thanks

**Comment by PivotalAnimal** [comment]
Hi @eduardoluizm -
From the source code, have you tried this fix? I see that IS4 references the "frameworks" element different than this repo. Maybe this is how the EF project should reference it as well although I would prefer to use latest netstandard and net461. SEE: [IS4 project.json](https://github.com/IdentityServer/IdentityServer4/blob/ad42ad0d492d55e59ead338f2b69f7d18771ea77/src/IdentityServer4/project.json#L22-30)

**Comment by PivotalAnimal** [comment]
Hi @eduardoluizm -
I just published to nuget using IS4 "frameworks". FYI - A good resource: [https://gist.github.com/davidfowl/8939f305567e1755412d6dc0b8baf1b7](https://gist.github.com/davidfowl/8939f305567e1755412d6dc0b8baf1b7)
