### ISSUE TITLE
Why do we need LoginPrivateKey.xml file

### ISSUE THREAD

**Issue by senzacionale** [PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore#16]
Hi, I like your project. But I would like to know why do we need LoginPrivateKey.xml file?

Is it possible to use for entity framework this project?
https://github.com/2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore

**Comment by PivotalAnimal** [comment]
@senzacionale it is not needed. I added it to show how someone could gain an extra level of security when signing in. In your code, simply remove this from the login controller. The project does use EF.

**Comment by senzacionale** [comment]
Thank yyou

**Comment by PivotalAnimal** [comment]
If your Relying Party uses JavaScript then keep it. Else remove. Compare my example with the Host project from IS4. I have added a few additional lines of code in Startup and LoginController that can be safely removed if you decide JS is not needed.

**Comment by PivotalAnimal** [comment]
There is also JavaScript that is referenced in the .cshtml of course that could be removed if need be.

**Comment by senzacionale** [comment]
I am working mostly with AngularJS, so I will leave it. Thank you
