### ISSUE TITLE
JWT token

### ISSUE THREAD

**Issue by senzacionale** [PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore#19]
Is it possible to get somehow back JWT token when you login with IdentityServer4? So to get back JSON web token with all needed info?

**Comment by PivotalAnimal** [comment]
If you request id_token using oidc you can get the sub identifier. sub can be used to query IUserService to return JWT tokens.

**Comment by senzacionale** [comment]
Do you have an example how you mean it?

**Comment by PivotalAnimal** [comment]
From LoginController, inside Index, you can use the user returned user from FindByUsername to query for JwtTokens. That call would be IUserService.GetJwtClaims. [`https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore/blob/master/BlueConcord.IdentityServer.Host/UI/Login/LoginController.cs`](https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore/blob/master/BlueConcord.IdentityServer.Host/UI/Login/LoginController.cs#L79)

**Comment by senzacionale** [comment]
Thanks, works like a charm :)
