### ISSUE TITLE
FindByUsername at LoginService must return Claims in IUser

### ISSUE THREAD

**Issue by eduardoluizm** [PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore#2]
I'm having a problem trying to  authenticate user.

During login, this method returns an user.
_loginService.FindByUsername(model.Username);

So, when I call _loginCookieService.IssueCookie(HttpContext, user, "idsvr", "password"), inside of this, I try to get claim values for UserApplications, but has 0 claims.

**Comment by PivotalAnimal** [comment]
@eduardoluizm have you tried the example from this repository? If you have seeded the database using the console application, it should work. SEE: BlueConcord.IdentityServer.EntityFrameworkCore.Common.Configuration.Clients / Scopes / Users. After you have seeded the database, try the MVC and API IS4 example against the Host project (again from this repository). If you wish to modify clients / scopes / claims, do so from the .Common project then re-run the Console App.

**Comment by eduardoluizm** [comment]
Sorry about delay..

I'm still having problems.

Look at this image. When I call FindByUsername(login).. it returns an ApplicationUser.. but the "included" Claims, are not loaded.. and I have a more than five claims in database.

![image](https://cloud.githubusercontent.com/assets/3385836/18225985/cada800e-71d6-11e6-881c-dd1c03217d79.png)

Maybe the query doesnt included Claims table during execution?

Thansks again.
